openapi: 3.0.0
info:
  title: Zoho Lens - fetchOrganizationsList
  description: Fetch the list of organizations
  version: 1.0.0
servers:
  - url: https://lens.zoho.{dc}
    description: Zoho Lens API server URL for your account region.
    variables:
      dc:
        enum:
          - com
          - eu
          - in
          - com.au
          - com.cn
          - jp
          - uk
          - sa
          - sg
          - ae
        default: com
        description: The data center domain corresponding to the account's region.
paths:
  /api/v2/organizations:
    get:
      summary: Fetch organizations list
      description: To fetch the list of organizations in Zoho Lens
      operationId: fetchOrganizationsList
      security:
        - iam-oauth2-schema:
          - ZohoLens.orgs.READ
      parameters:
        - name: x-com-zoho-lens-orgid
          in: header
          required: true
          schema:
            type: string
          description: Zoho Lens Organization ID
      responses:
        "200":
          description: Fetched organizations list successfully
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    iam-oauth2-schema:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.com/oauth/v2/auth
          tokenUrl: https://accounts.zoho.com/oauth/v2/token
          scopes:
            ZohoLens.orgs.READ: Read access to Zoho Lens organizations
